version: '3'

services:
  web:
    build:
      context: .
    command: python3 manage.py runserver -h "0.0.0.0" -p 5000 -d

    env_file:
      - ./.env.prod

    volumes:
      - .:/api
    ports:
      - 5000:5000